### ISSUE TITLE
Bug introduced in 2.9.x: c.getComputedStyle is not a function

### ISSUE THREAD

**Issue by barboite** [1904labs/dom-to-image-more#52]
### Trying to use dom-to-image with angular 12.x
```

import domtoimage from 'dom-to-image-more';
export class MyComponent {
    @ViewChild('leafletMap') leafletMap: ElementRef;
    
    downloadMap = (): void => {
        //error happens here
        domtoimage.toPng(this.leafletMap.nativeElement).then((img: any) => {
            console.log(img);
        });
    };
}
/* of course this is simplified */

```
c.getComputedStyle is not a function is thrown. Strangely enough, this exact same code works with 2.8.0
[stackoverflow answer & stackblitz](https://stackoverflow.com/a/69540700/5677252)

### Library version
2.9.x
### Browsers

all

**Comment by talhaamjadx** [comment]
@barboite were you able to fix this issue?

**Comment by barboite** [comment]
@talhaamjadx mmhhh, tried to paste this in my `node_modules/dom-to-image-more/src/dom-to-image-more.js` and re-built my front. It doesn't work, still the same error. Am i supposed to re-install deps with npm ? i'm not familiar with modifying inside node_modules

**Comment by SNDST00M** [comment]
The latest commits also contain a unreleased fix for the Karma test workflow. Any ETA on release @IDisposable?

**Comment by IDisposable** [comment]
Should be fixed in v2.9.4

**Comment by 19BC83** [comment]
Unfortunately it's not fixed with v2.9.4 - the problem persits as mentioned in #42 . Downgrading to v2.8.0 solves the problem and is still working properly without TypeError in my project.

**Comment by IDisposable** [comment]
Can you please point me at a source code reproduction of this issue?

**Comment by SNDST00M** [comment]
Also I hate to be "that techie" but could you confirm the cache been sufficiently cleared to ensure that it was indeed 2.9.4 throwing the error?

**Comment by 19BC83** [comment]
> Also I hate to be "that techie" but could you confirm the cache been sufficiently cleared to ensure that it was indeed 2.9.4 throwing the error?

Thanks for your hint.

Procedure, starting from a flawless Angular v13 project (no error running v2.8.0):
=> npm i dom-to-image-more@latest => clearing browser-cache => restarting dev-server => failure with TypeError
=> npm i dom-to-mage-more@2.8.0 => restarting dev-server => project is running flawlessly again

Any objections?

**Comment by SNDST00M** [comment]
Could you paste that TypeError log here?

**Comment by 19BC83** [comment]
> Could you paste that TypeError log here?

The TypeError is mentioned in #42.

**Comment by IDisposable** [comment]
Fixed in v2.9.5, sorry for the inability to test before...

**Comment by IDisposable** [comment]
Closing since nobody has complained that v2.9.5 didn't fix this more than a year ago :)
