### ISSUE TITLE
TypeError after upgrading to 2.9.1

### ISSUE THREAD

**Issue by 19BC83** [1904labs/dom-to-image-more#42]
First of all: Thanks for this fantastic project!

I am using dom-to-image-more in combination with pdfmake. Since upgrading to version 2.9.1 I am receiving a TypeError in browser console:

`ERROR Error: Uncaught (in promise): TypeError: c.getComputedStyle is not a function
TypeError: c.getComputedStyle is not a function
    at P (dom-to-image-more.min.js:3)
    at e (dom-to-image-more.min.js:3)
    at ZoneDelegate.invoke (zone.js:372)
    at Object.onInvoke (core.js:28672)
    at ZoneDelegate.invoke (zone.js:371)
    at Zone.run (zone.js:134)
    at zone.js:1276
    at ZoneDelegate.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28659)
    at ZoneDelegate.invokeTask (zone.js:405)
    at resolvePromise (zone.js:1213)
    at resolvePromise (zone.js:1167)
    at zone.js:1279
    at ZoneDelegate.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28659)
    at ZoneDelegate.invokeTask (zone.js:405)
    at Zone.runTask (zone.js:178)
    at drainMicroTaskQueue (zone.js:582)
    at invokeTask (zone.js:491)
    at ZoneTask.invoke (zone.js:476)`

Downgrading to version 2.8.0 solves the problem. A fix would be appreciated.

**Comment by IDisposable** [comment]
Can you point me at a repro of this issue... none of the tests I have show this issue. What environment are you running on?

**Comment by 19BC83** [comment]
> Can you point me at a repro of this issue... none of the tests I have show this issue. What environment are you running on?

Thanks for working on this issue!
I am using Angular 13.0.3 generating pdfs with pdfmake (v.0.2.4) including svgs from DOM with dom-to-image-more 2.8.0. I will try(!) to make Stackblitz example in order to allow a reproduction.

**Comment by 19BC83** [comment]
[Stackblitz Example](https://stackblitz.com/edit/angular-ivy-vhhttk?file=src/app/app.component.ts)

Its working with dom-to-image-more v2.8.0. Changing package to v2.9.4 results in the console output mentioned above.

**Comment by IDisposable** [comment]
Now working on v2.9.5 for your Stackblitz. THANK YOU for the repro.

**Comment by 19BC83** [comment]
I can confirm: (Finally) no more TypeError and running flawlessly with v2.9.5! Good job - thank you!!
